projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ca-central-1
        apiId: po3yhvkiavc3rptmzxmpfm3s64
        frontend: javascript
        framework: react
        maxDepth: 5
extensions:
  amplify:
    version: 3
