repos:
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.83.3
    hooks:
      - id: cfn-lint-rc
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
